# Generated by Django 4.2.6 on 2023-10-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forla_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
